### ISSUE TITLE
Corrupt images

### ISSUE THREAD

**Issue by tobsen** [sketch-hq/fig2sketch#64]
I get `CRITICAL:root:Could not convert image xxx. It appears to be corrupted.` with one file. `--force-convert-images` does also not work. Is there any way in Figma to figure out wich image this is? Or do you plan an option to ignore those images and maybe replace them with with a marked rectangle?

**Comment by javitonino** [comment]
Hi! :wave: 

Due to the way we load the images at the moment, it's difficult to provide context about where an image is being used. Recent .fig files (created in the last 3 months or so) are actually .zip archives, so you can try unzipping it and looking at the image file inside (should be under the `images/` directory inside the .fig).

If you manage to identify the image and you can share it with us, it would be great, we can take a look and see if we can relax our checks to allow it. So far, we've only had one document in our tests with corrupted images and it could be solved with the `--force-convert-images` flag.

About your suggestion to replace the images with a marked rectangle: I'd prefer if we could fix it and import the image somehow. But your idea is not a bad choice for the cases where we really cannot import it. It's complicated to do this in the current code for the same reason it's hard to provide better context, but if we see a few documents running into this problem, we'll definitely take a look at it.

**Comment by tobsen** [comment]
Hi!

I did what you suggested. Seems that this are broken PNGs. After splitting the file in Figma I managed to find them, even though they were not visible since there was nothing to display. Unfortunately I can't say how these were created in Figma, the part of the document was not mine.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/132219/205275390-12332f60-6b3a-462a-99ba-67b5fec85c28.png">

[corrupt-images.fig.zip](https://github.com/sketch-hq/fig2sketch/files/10140336/corrupt-images.fig.zip)
