### ISSUE TITLE
Exported sketch file size question

### ISSUE THREAD

**Issue by Fupete** [sketch-hq/fig2sketch#89]
The starting `.fig` file is 20 MB.
The size of the exported `.sketch` file is 500 MB. 
If I open the file in Sketch App and save it again, it becomes 37.7 MB. 
Is this a compression issue? Am I missing something in the options? 

----
MacOS, Mini M1, Ventura 13.1

**Comment by javitonino** [comment]
Yes, we are not compressing the archives at all, this is on purpose. 

Our main usage for fig2sketch is inside Sketch, where it is used when you open a file. The .fig is converted and immediately open by Sketch, so skipping compression leads to faster time (no need to compress nor decompress) and the size is not an issue since it's only being used as a temporary file.

Is your use case different? I might imagine this might be troublesome if you are archiving the output of fig2sketch directly. Instead, you could open/save the document with Sketch (as you mentioned), recompress the file with any standard zip tools, or modify the code to pass the `compression=ZIP_DEFLATED` option to Zipfile here: https://github.com/sketch-hq/fig2sketch/blob/main/src/fig2sketch.py#L93 (if you decide to do this and add a command line parameter, we'd be happy to receive a pull request).

**Comment by Fupete** [comment]
@javitonino ⬆ this PR 🙃 comes from my friend and teammate @bfabio 💙 

We will publish regularly each version/test (native Figma in progress, and the exported sketch using your fig2sketch) we will do upcoming weeks here on our [design-ui-kit v3 temporary branch](https://github.com/italia/design-ui-kit/tree/feat/next-ui-kit-v3).

We have yet a couple of things to fix in Figma naming conventions, and so on, but it starts to be nice also the exported sketch one, we have a path. We will open more issues and PR if we find anything useful ✋ Tx again for your work.

**Comment by javitonino** [comment]
Just merged it. Thanks for letting us know what you are working on. We are glad this project helped you make your UI kit available for more designers :smile:
